#!/bin/bash

help() {
	echo "
  installpkg is a PKGBUILD fetcher and installer, using [pkg-name] or stdout.

  Usage: installpkg [option] [pkg-name]
  options:
    -p|--print = Get PKGBUILD, print and exit"
	exit
}

while [[ $# -gt 0 ]]; do
	case $1 in
	-p | --print) INSTALL_PB=0 ;;
	-h | --help) help ;;
	-*)
		echo "Unknown param: $1"
		exit 1
		;;
	*)
		INSTALL_PB=1
		break
		;;
	esac
	shift
done

pkgs=$1
if [[ -z $pkgs ]]; then
	pkgs="$(cat)"
	if [[ -z $pkgs ]]; then
		echo "No package specified"
		exit
	fi
fi
basedir=${AUR_BUILD_DIR:-$HOME/.cache/build/}
if [[ ! -d $basedir ]]; then mkdir -p "$basedir"; fi

cd $basedir

while IFS="\n" read -r pkg; do
	git -C ${pkg} pull || git clone https://aur.archlinux.org/${pkg}.git
	if [[ $? != 0 ]]; then
		echo "Package '$pkg' not found"
		exit
	fi

	if [[ $INSTALL_PB == 0 ]]; then
		cat ${pkg}/PKGBUILD
	elif [[ $INSTALL_PB == 1 ]]; then
		cd ${pkg}
		makepkg -si
	fi

	echo
done <<<$pkgs
