#!/bin/bash

help() {
	echo "
  pb-get is a PKGBUILD fetcher for AUR packages.

  Usage: pb-get [option] <pkg-name>
  Options:
    -p = Print PKGBUILD
    -h = Print this screen"
	exit
}

if [[ -z $1 ]]; then
	help
fi

while [[ $# -gt 0 ]]; do
	case $1 in
	-p) PRINT_PB=1 ;;
	-h | --help) help ;;
	-*)
		echo "Unknown param: $1"
		exit 1
		;;
	*) break ;;
	esac
	shift
done

pkg=$1
if [[ -z $1 ]]; then
	echo "No package specified"
	exit
fi
basedir=${AUR_BUILD_DIR:-$HOME/.cache/aur-build/}
if [[ ! -d $basedir ]]; then mkdir -p "$basedir"; fi

cd $basedir

git -C ${pkg} pull || git clone https://aur.archlinux.org/${pkg}.git
if [[ $? != 0 ]]; then
	echo "Package '$pkg' not found"
	exit
fi

if [[ $PRINT_PB != 1 ]]; then
	cat ${pkg}/PKGBUILD
fi
